config/routes.rb
WhosUsingWhatWeb::Application.routes.draw do

  resources :anewtables
  resources :somethings
  resources :person_searches
  resources :company_searches
  resources :whos_using_what
  resources :searches
  resources :calculators

  #this is way to limit to only GET, POST, etc for specific controller methods
=begin
  resources :searches, :collection => {
       :search => :post
  }
=end

  resources :sessions

  ENV['home_url'] = "/"

  match 'company_search/search', :to => 'company_searches#search'

  #this is for oauth re-routing
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/loginstatus', :to => 'sessions#loginstatus'

  match 'people/search', :to => 'searches#search'
  match 'login', :to => 'sessions#create'
  match 'logout', :to => 'sessions#destroy'

  match 'calculator', :to => 'calculators#new'

  match 'authenticate', :to => 'sessions#new'

  #map.connect 'searches/calculator', :controller => 'searches', :action => 'calculator'

  root :to => "searches#new"

  match ':action' => 'static#:action'


end

app/models/something.rb
class Something < ActiveRecord::Base
  attr_accessible :db, :rake
end

app/controllers/somethings_controller.rb
class SomethingsController < ApplicationController
  # GET /somethings
  # GET /somethings.json
  def index
    @somethings = Something.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @somethings }
    end
  end

  # GET /somethings/1
  # GET /somethings/1.json
  def show
    @something = Something.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @something }
    end
  end

  # GET /somethings/new
  # GET /somethings/new.json
  def new
    @something = Something.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @something }
    end
  end

  # GET /somethings/1/edit
  def edit
    @something = Something.find(params[:id])
  end

  # POST /somethings
  # POST /somethings.json
  def create
    @something = Something.new(params[:something])

    respond_to do |format|
      if @something.save
        format.html { redirect_to @something, notice: 'Something was successfully created.' }
        format.json { render json: @something, status: :created, location: @something }
      else
        format.html { render action: "new" }
        format.json { render json: @something.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /somethings/1
  # PUT /somethings/1.json
  def update
    @something = Something.find(params[:id])

    respond_to do |format|
      if @something.update_attributes(params[:something])
        format.html { redirect_to @something, notice: 'Something was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @something.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /somethings/1
  # DELETE /somethings/1.json
  def destroy
    @something = Something.find(params[:id])
    @something.destroy

    respond_to do |format|
      format.html { redirect_to somethings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/somethings_helper.rb
module SomethingsHelper
end

app/views/somethings/_form.html.erb
<%= form_for(@something) do |f| %>
  <% if @something.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@something.errors.count, "error") %> prohibited this something from being saved:</h2>

      <ul>
      <% @something.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rake %><br />
    <%= f.text_field :rake %>
  </div>
  <div class="field">
    <%= f.label :db %><br />
    <%= f.text_field :db %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/somethings/edit.html.erb
<h1>Editing something</h1>

<%= render 'form' %>

<%= link_to 'Show', @something %> |
<%= link_to 'Back', somethings_path %>

app/views/somethings/index.html.erb
<h1>Listing somethings</h1>

<table>
  <tr>
    <th>Rake</th>
    <th>Db</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @somethings.each do |something| %>
  <tr>
    <td><%= something.rake %></td>
    <td><%= something.db %></td>
    <td><%= link_to 'Show', something %></td>
    <td><%= link_to 'Edit', edit_something_path(something) %></td>
    <td><%= link_to 'Destroy', something, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Something', new_something_path %>

app/views/somethings/new.html.erb
<h1>New something</h1>

<%= render 'form' %>

<%= link_to 'Back', somethings_path %>

app/views/somethings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rake:</b>
  <%= @something.rake %>
</p>

<p>
  <b>Db:</b>
  <%= @something.db %>
</p>


<%= link_to 'Edit', edit_something_path(@something) %> |
<%= link_to 'Back', somethings_path %>