config/routes.rb
WhosUsingWhatWeb::Application.routes.draw do

  resources :anewtables
  resources :somethings
  resources :person_searches
  resources :company_searches
  resources :whos_using_what
  resources :searches
  resources :calculators

  #this is way to limit to only GET, POST, etc for specific controller methods
=begin
  resources :searches, :collection => {
       :search => :post
  }
=end

  resources :sessions

  ENV['home_url'] = "/"

  match 'company_search/search', :to => 'company_searches#search'

  #this is for oauth re-routing
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/loginstatus', :to => 'sessions#loginstatus'

  match 'people/search', :to => 'searches#search'
  match 'login', :to => 'sessions#create'
  match 'logout', :to => 'sessions#destroy'

  match 'calculator', :to => 'calculators#new'

  match 'authenticate', :to => 'sessions#new'

  #map.connect 'searches/calculator', :controller => 'searches', :action => 'calculator'

  root :to => "searches#new"

  match ':action' => 'static#:action'


end

app/models/person_search.rb
class PersonSearch < ActiveRecord::Base
  attr_accessible :programming_language, :page_number, :zipcode, :exclude_recruiters

end

app/controllers/person_searches_controller.rb
class PersonSearchesController < ApplicationController
  # GET /person_searches
  # GET /person_searches.json
  def index
    @person_searches = PersonSearch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @person_searches }
    end
  end

  # GET /person_searches/1
  # GET /person_searches/1.json
  def show
    @person_search = PersonSearch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person_search }
    end
  end

  # GET /person_searches/new
  # GET /person_searches/new.json
  def new
    @person_search = PersonSearch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person_search }
    end
  end

  # GET /person_searches/1/edit
  def edit
    @person_search = PersonSearch.find(params[:id])
  end

  # POST /person_searches
  # POST /person_searches.json
  def create
    @person_search = PersonSearch.new(params[:person_search])

    respond_to do |format|
      if @person_search.save
        format.html { redirect_to @person_search, notice: 'Person search was successfully created.' }
        format.json { render json: @person_search, status: :created, location: @person_search }
      else
        format.html { render action: "new" }
        format.json { render json: @person_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /person_searches/1
  # PUT /person_searches/1.json
  def update
    @person_search = PersonSearch.find(params[:id])

    respond_to do |format|
      if @person_search.update_attributes(params[:person_search])
        format.html { redirect_to @person_search, notice: 'Person search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /person_searches/1
  # DELETE /person_searches/1.json
  def destroy
    @person_search = PersonSearch.find(params[:id])
    @person_search.destroy

    respond_to do |format|
      format.html { redirect_to person_searches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/person_searches_helper.rb
module PersonSearchesHelper
end

app/views/person_searches/_form.html.erb
<%= form_for(@person_search) do |f| %>
  <% if @person_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person_search.errors.count, "error") %> prohibited this person_search from being saved:</h2>

      <ul>
      <% @person_search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :programming_language %><br />
    <%= f.text_field :programming_language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/person_searches/edit.html.erb
<h1>Editing person_search</h1>

<%= render 'form' %>

<%= link_to 'Show', @person_search %> |
<%= link_to 'Back', person_searches_path %>

app/views/person_searches/index.html.erb
<h1>Listing person_searches</h1>

<table>
  <tr>
    <th>Zipcode</th>
    <th>Programming language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person_searches.each do |person_search| %>
  <tr>
    <td><%= person_search.zipcode %></td>
    <td><%= person_search.programming_language %></td>
    <td><%= link_to 'Show', person_search %></td>
    <td><%= link_to 'Edit', edit_person_search_path(person_search) %></td>
    <td><%= link_to 'Destroy', person_search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person search', new_person_search_path %>

app/views/person_searches/new.html.erb
<h1>New person_search</h1>

<%= render 'form' %>

<%= link_to 'Back', person_searches_path %>

app/views/person_searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zipcode:</b>
  <%= @person_search.zipcode %>
</p>

<p>
  <b>Programming language:</b>
  <%= @person_search.programming_language %>
</p>


<%= link_to 'Edit', edit_person_search_path(@person_search) %> |
<%= link_to 'Back', person_searches_path %>