config/routes.rb
WhosUsingWhatWeb::Application.routes.draw do

  resources :anewtables
  resources :somethings
  resources :person_searches
  resources :company_searches
  resources :whos_using_what
  resources :searches
  resources :calculators

  #this is way to limit to only GET, POST, etc for specific controller methods
=begin
  resources :searches, :collection => {
       :search => :post
  }
=end

  resources :sessions

  ENV['home_url'] = "/"

  match 'company_search/search', :to => 'company_searches#search'

  #this is for oauth re-routing
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  match '/loginstatus', :to => 'sessions#loginstatus'

  match 'people/search', :to => 'searches#search'
  match 'login', :to => 'sessions#create'
  match 'logout', :to => 'sessions#destroy'

  match 'calculator', :to => 'calculators#new'

  match 'authenticate', :to => 'sessions#new'

  #map.connect 'searches/calculator', :controller => 'searches', :action => 'calculator'

  root :to => "searches#new"

  match ':action' => 'static#:action'


end

app/controllers/anewtables_controller.rb
class AnewtablesController < ApplicationController
  # GET /anewtables
  # GET /anewtables.json
  def index
    @anewtables = Anewtable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anewtables }
    end
  end

  # GET /anewtables/1
  # GET /anewtables/1.json
  def show
    @anewtable = Anewtable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anewtable }
    end
  end

  # GET /anewtables/new
  # GET /anewtables/new.json
  def new
    @anewtable = Anewtable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anewtable }
    end
  end

  # GET /anewtables/1/edit
  def edit
    @anewtable = Anewtable.find(params[:id])
  end

  # POST /anewtables
  # POST /anewtables.json
  def create
    @anewtable = Anewtable.new(params[:anewtable])

    respond_to do |format|
      if @anewtable.save
        format.html { redirect_to @anewtable, notice: 'Anewtable was successfully created.' }
        format.json { render json: @anewtable, status: :created, location: @anewtable }
      else
        format.html { render action: "new" }
        format.json { render json: @anewtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anewtables/1
  # PUT /anewtables/1.json
  def update
    @anewtable = Anewtable.find(params[:id])

    respond_to do |format|
      if @anewtable.update_attributes(params[:anewtable])
        format.html { redirect_to @anewtable, notice: 'Anewtable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anewtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anewtables/1
  # DELETE /anewtables/1.json
  def destroy
    @anewtable = Anewtable.find(params[:id])
    @anewtable.destroy

    respond_to do |format|
      format.html { redirect_to anewtables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/anewtables_helper.rb
module AnewtablesHelper
end

app/views/anewtables/_form.html.erb
<%= form_for(@anewtable) do |f| %>
  <% if @anewtable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anewtable.errors.count, "error") %> prohibited this anewtable from being saved:</h2>

      <ul>
      <% @anewtable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tablevalue %><br />
    <%= f.text_field :tablevalue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anewtables/edit.html.erb
<h1>Editing anewtable</h1>

<%= render 'form' %>

<%= link_to 'Show', @anewtable %> |
<%= link_to 'Back', anewtables_path %>

app/views/anewtables/index.html.erb
<h1>Listing anewtables</h1>

<table>
  <tr>
    <th>Tablevalue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anewtables.each do |anewtable| %>
  <tr>
    <td><%= anewtable.tablevalue %></td>
    <td><%= link_to 'Show', anewtable %></td>
    <td><%= link_to 'Edit', edit_anewtable_path(anewtable) %></td>
    <td><%= link_to 'Destroy', anewtable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anewtable', new_anewtable_path %>

app/views/anewtables/new.html.erb
<h1>New anewtable</h1>

<%= render 'form' %>

<%= link_to 'Back', anewtables_path %>

app/views/anewtables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tablevalue:</b>
  <%= @anewtable.tablevalue %>
</p>


<%= link_to 'Edit', edit_anewtable_path(@anewtable) %> |
<%= link_to 'Back', anewtables_path %>